spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 1368
  redis:
    host: localhost
    port: 6379
server:
  port:  8080
jwt:
  secret-key: hanjaejung-create.board_project_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000


